- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: jeongeok.park-hongkong
    instance_type: t2.micro
    security_group: jeongeok-server-sg
    image: jeongeok-ami
    region: ap-east-1

  tasks:
    - name: Launch instance
      amazon.aws.ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-05f50d25447c09f51
         assign_public_ip: yes
      register: ec2